### ISSUE TITLE
question about jul_13_2017_experiment.clj

### ISSUE THREAD

**Issue by monperrus** [jsa-aerial/DMM#4]
`examples/dmm/quil-controlled/jul_13_2017_experiment.clj` now runs, thanks.

what is it meant to do? where is the DMM program itself?

**Comment by anhinga** [comment]
This is a small DMM which should accumulate the list of mouse clicks and render them in an associated graphics windows. Let me know, if it does that for you.

It is mostly meant to illustrate that if one uses a neural network based on flows of vectors (in this case, flows of V-values which are vectors based on nested dictionaries) instead of flows of numbers, then it is easy to implement usual programming operations such as consing the list, which are pretty difficult to implement within the conventional neural nets.

The network itself is defined in lines 38-78 of this file. It consists of 3 neurons:

* the Self neuron (with "v-accum" activation function and name ":self") which holds the network matrix (which does not change in this particular example, but in general the network is capable of modifying itself (see jul_6 example for that));

* the neuron tracking the mouse clicks and emitting the mouse position on mouse clicks (with activation function "v-mouse-pressed-monitor" and name ":mouse-pressed-monitor")

* the neuron accumulating the list of meaningful inputs (with activation function "v-dmm-cons" and name ":my-list")

(There is also an active neuron with activation function "v-mouse-coords" and name ":mouse-position" left from jul_12 experiment, but in this network it is not connected to anything besides itself. It emits the current mouse coords regardless of clicks. I pondered whether to remove it from this network altogether, but decided to keep it here.)

(With this formalism, one can have rather powerful neurons, if one wants to, so the programs/networks often have a small number of them.)

**Comment by anhinga** [comment]
I've just recorded this as a piece of documentation

https://github.com/jsa-aerial/DMM/blob/master/examples/dmm/quil-controlled/comment_to_jul_13_2017_experiment.md

linked from https://github.com/jsa-aerial/DMM/blob/master/examples/dmm/quil-controlled/README.md

**Comment by monperrus** [comment]
thanks!
